# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - mysql

before_install:
  - mysql -e 'create database tracker;'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту mr.alexey.taranov@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      - mr.alexey.taranov@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="b4218142-9161-4677-9ad7-291d27305c04"

jdk:
  - openjdk11